fruitPrice1:
  max: 140
  min: 80
  priceVarianceMax : 50

fruitPrice2:
  max: 180
  min: 120
  priceVarianceMax : 30

fruitPrice3:
  max: 80
  min: 50
  priceVarianceMax : 20

driveCost:
  max: 50
  min: 10

#Currently only supports one of resultscheck to be enable at each time
resultCheck:
  lowestCost: 1
  lowestCostWithCart: 0


shoppingCart:
  mandatoryKind: ["fruitPrice3"]
  optionalKind: ["fruitPrice1","fruitPrice2"]  
  

